### ISSUE TITLE
[0001] Import doesnt work in node enviroments

### ISSUE THREAD

**Issue by PRDeving** [PRDeving/PocketDataBase2.0#1]
fs doesn't returns the file content, probably should wait for callback.

Probably an async issue.

TypeError: Cannot read property 'length' of undefined
    at _import [as Import](/Users/pablodeving/Sites/PocketDataBase2.0/src/pdb.js:284:17)
    at repl:1:5
    at REPLServer.defaultEval (repl.js:269:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval](domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:439:12)
    at emitOne (events.js:95:20)
    at REPLServer.emit (events.js:182:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)

**Comment by PRDeving** [comment]
Fixed in commit 4038313139b1851b12730b7d416e3394570d9d48 PDB v2.0.2
